FROM python:3.11.9-slim-bullseye

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg curl \
        git \
        wget \
    && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash  \
    && apt-get install git-lfs -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

